### ISSUE TITLE
Mask treats unmarked segments as clean

### ISSUE THREAD

**Issue by mabhijithn** [exporl/mwf-artifact-removal#1]
The documentation of the toolbox says that only data till the last marked artefact is used for filter computation. But it does not seem to be the case. Mask generated has 0s in unmarked segments which is later used in creating the matrix of clean (artefact free) data. Hence, unmarked segments are treated as clean.

**Comment by ben-somers** [comment]
Can you tell me how to reproduce this issue? Do you use mwf_getmask with EEGLAB to perform the manual marking? In that case, the code below should take care of replacing all segments after the last artifact segment with NaNs:

https://github.com/exporl/mwf-artifact-removal/blob/6f28220d253c3806b8a5091842eb0a79e90b2b1a/mwf/mwf_getmask.m#L153-L155

Note that in mwf_params.m, there is an option to specify how NaNs are treated. By default this is 'ignore', but if for some reason it is put on 'clean' then NaNs in the masked are treated as clean data.

**Comment by mabhijithn** [comment]
It was my colleague who was having the issue. It seems the toolbox she downloaded did not have this portion. Strange. Now, she has cloned the repository and this code is present. No issue then.
