### ISSUE TITLE
Likely numerical issues resulting in non-symmetric covariances

### ISSUE THREAD

**Issue by mabhijithn** [exporl/mwf-artifact-removal#2]
When applying mwf_compute to certain data covariances Ryy and Rnn could be non-symmetric. Mathematically it is not possible, but precision issues in MATLAB may cause it. This will lead to complex eigen values in GEVD.
Suggestion: force Ryy and Rnn to be symmetric. For eg:
Ryy = (Ryy+Ryy')./2;

**Comment by ben-somers** [comment]
Commit https://github.com/exporl/mwf-artifact-removal/commit/8db80e260b658766c4871adb0e339ae81ecd5ea9 should resolve the issue.
